### ISSUE TITLE
Elasticsearch-1 configuration doesn't work - invalid combination error

### ISSUE THREAD

**Issue by lukaszkorecki** [Stackdriver/stackdriver-agent-service-configs#41]
When testing the config worked as expected when using graphite as output, however it fails for write_gcm plugin:

```
 "message": "Unsupported collectd plugin/type combination: plugin: \"curl_json\" type: \"gauge\""#012
```

Should it use custom metric types like Statsd config? (which works great btw)

**Comment by igorpeshansky** [comment]
Glad to hear that statsd works for you. This one should have worked too, however.
Looks like one of the values didn't get rewritten properly. All of the values sent to Stackdriver with this config should have the plugin set to "elasticsearch".
Are you using the unmodified version of the config? Are there any other error/warning messages in the log?

**Comment by lukaszkorecki** [comment]
Yeah, I tried the unmodified version + set syslog plugin to debug. Here's the log message: 

```
Mar 24 10:29:15 test-es-proxy collectd[6403]: write_gcm: Server response (CollectdTimeseriesRequest) contains errors:#012{#012  "payloadErrors": [#012    {#012      "index": 65,#012      "error": {#012        "code": 3,#012        "message": "Unsupported collectd plugin/type combination: plugin: \"curl_json\" type: \"gauge\""#012      }#012    },#012    {#012      "index": 66,#012      "error": {#012        "code": 3,#012        "message": "Unsupported collectd plugin/type combination: plugin: \"curl_json\" type: \"gauge\""#012      }#012    },#012    {#012      "index": 67,#012      "error": {#012        "code": 3,#012        "message": "Unsupported collectd plugin/type combination: plugin: \"curl_json\" type: \"gauge\""#012      }#012    },#012    {#012      "index": 68,#012      "error": {#012        "code": 3,#012        "message": "Unsupported collectd plugin/type combination: plugin: \"curl_json\" type: \"gauge\""#012      }#012    },#012    {#012      "index": 69,#012      "error": {#012        "code": 3,#012        "message": "Unsupported collectd plugin/type combination: plugin: \"curl_json\" type: \"gauge\""#012      }#012    },#012    {#012      "index": 70

```

Needless to say other metrics (df, cpu etc) work as expected.

**Comment by jkohen** [comment]
We hope this has been solved. In the meantime, the ElasticSearch plugin is no longer supported. Please read https://cloud.google.com/monitoring/agent/plugins/elasticsearch for options

**Comment by lukaszkorecki** [comment]
@jkohen No problem, we've ended up writing a small monitoring daemon in Clojure to send ES stats to Collectd 👍

**Comment by jkohen** [comment]
Thanks for the update. Sorry for the delay.
