### ISSUE TITLE
Configuration file for Oracle DB?

### ISSUE THREAD

**Issue by saurabh3896** [Stackdriver/stackdriver-agent-service-configs#48]
I see that there exist config files exists for mysql and postgresql. Since Oracle is also a SQL database, will it work by "tweaking" the .conf file for mysql/postgresql or Stackdriver simply doesn't support the monitoring for Oracle DB?

**Comment by igorpeshansky** [comment]
Unfortunately, there's more to it than that. These configurations encode the curated data that Stackdriver is prepared to receive, with support on the server side for processing that data and displaying curated dashboards (see https://cloud.google.com/monitoring/agent/plugins/). Stackdriver does not have a curated monitoring experience for Oracle databases.
That said, you definitely should be able to use these configs as an inspiration or a starting point to build a custom metrics-based solution for your case (see https://cloud.google.com/monitoring/agent/custom-metrics-agent).

**Comment by saurabh3896** [comment]
Sorry for asking again. I wanted to confirm the required changes for this. From the documentation, looks like I just need to create a file at `/opt/stackdriver/collectd/etc/collectd.d/my-custom-config.conf` and restart the agent. Do I also need to modify the conf file at `/etc/stackdriver/collectd.conf` ?

**Comment by igorpeshansky** [comment]
@saurabh3896 You don't need to modify the main config — the agent will find any files in the include location automatically upon restart.
Note that the preferred location for custom configs these days is `/etc/stackdriver/collectd.d/` (although the location you mentioned will still be recognized).

**Comment by saurabh3896** [comment]
Also, I saw the there are no library files for oracle plugin (`oracle.so` and `oracle.la`) in the `lib/collectd` folder. I wanted to confirm if I also have to recompile the stackdriver agent to include oracle plugin? Thanks for your time. @igorpeshansky

**Comment by igorpeshansky** [comment]
That's correct, @saurabh3896, we don't bundle the `oracle` plugin into the `stackdriver-agent` package. It would be hard to compile a version separately that would work with the agent package — your best bet would be to rebuild the whole package into a `.deb` or a `.rpm`, and enable the `oracle` plugin in the `configure` phase. You can use the https://github.com/Stackdriver/agent-packaging repo to build the package.
