### ISSUE TITLE
How could we get the GCP VM instance file descriptors metrics  from stackdriver agent?

### ISSUE THREAD

**Issue by hixichen** [Stackdriver/stackdriver-agent-service-configs#53]
https://cloud.google.com/monitoring/api/metrics_gcp#gcp-compute

I am surprised that there is no file descriptor item for compute

**Comment by igorpeshansky** [comment]
The GCP compute metrics are not sent by the agent, but by the GCE infrastructure. The agent metrics are at https://cloud.google.com/monitoring/api/metrics_agent.
However, they indeed don't contain the count of open file descriptors.

The per-process file descriptors will eventually be available from the `processes` plugin, but that would require a major version release of the Stackdriver monitoring agent. We don't currently have an ETA for that.
For VM-level open file descriptors counts, you could use something like [this](https://mailman.verplant.org/pipermail/collectd/2012-March/005037.html) with the [Custom metrics from the agent](https://cloud.google.com/monitoring/agent/custom-metrics-agent) mechanism, which will add Stackdriver custom metrics in your project.
Hope this helps.

**Comment by hixichen** [comment]
I did some research: 

the limit of one process would be the one we want to monitor. 
And, it referred to pre-process file descriptors
```
The per-process file descriptors will eventually be available from the processes plugin, but that would require a major version release of the Stackdriver monitoring agent. We don't currently have an ETA for that.
```

**Comment by hixichen** [comment]
hope stackdriver agent can work like https://github.com/influxdata/telegraf/tree/master/plugins/inputs/procstat
